/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prezantimi;

import data.vdhoma;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.fdhoma;

/**
 *
 * @author geraldo
 */
public class frmdhoma extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmdhoma
     */
    public frmdhoma() {
        initComponents();
            moster("");
        inavantazh();
        

    }
    

    private String accion = "ruaj";

    void fshehje_kolone() {
        listtabele.getColumnModel().getColumn(0).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(0).setMinWidth(0);
        listtabele.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    void inavantazh() {
        txtiddhoma.setVisible(false);
        cbopersonat.setEnabled(false);
        txtnumri.setEnabled(false);
        txtpershkrimi.setEnabled(false);
        txtkarakteristika.setEnabled(false);
        txtpagesa.setEnabled(false);
        cbodhoma_e_zene.setEnabled(false);
        cbotipi_dhomave.setEnabled(false);

        btnruaj.setEnabled(false);
        btnkancelo.setEnabled(false);
        btnelimino.setEnabled(false);
        txtiddhoma.setText("");
        txtpagesa.setText("");
        txtkarakteristika.setText("");
        txtpershkrimi.setText("");

    }

    void avantazh() {
        txtiddhoma.setVisible(false);

        cbopersonat.setEnabled(true);
        txtnumri.setEnabled(true);
        txtpershkrimi.setEnabled(true);
        txtkarakteristika.setEnabled(true);
        txtpagesa.setEnabled(true);
        cbodhoma_e_zene.setEnabled(true);
        cbotipi_dhomave.setEnabled(true);

        btnruaj.setEnabled(true);
        btnkancelo.setEnabled(true);
        btnelimino.setEnabled(true);
        txtiddhoma.setText("");
        txtpagesa.setText("");
        txtkarakteristika.setText("");
        txtpershkrimi.setText("");

    }

    void moster(String kerko) {
        try {
            DefaultTableModel model;
            fdhoma func = new fdhoma();
            model = func.mostervizit(kerko);

            listtabele.setModel(model);
            fshehje_kolone();
            lbltotalregjister.setText("Total Regjister " + Integer.toString(func.totalregjister));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtiddhoma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnumri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbopersonat = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpershkrimi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtkarakteristika = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtpagesa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbodhoma_e_zene = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbotipi_dhomave = new javax.swing.JComboBox();
        btne_re = new javax.swing.JButton();
        btnruaj = new javax.swing.JButton();
        btnkancelo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtkerko = new javax.swing.JTextField();
        btnkerko = new javax.swing.JButton();
        btnelimino = new javax.swing.JButton();
        btnshtepi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listtabele = new javax.swing.JTable();
        lbltotalregjister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Dhoma");

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Regjistri i dhomave"));

        jLabel2.setText("Numri:");

        txtnumri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumriActionPerformed(evt);
            }
        });

        jLabel3.setText("Personat:");

        cbopersonat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cbopersonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopersonatActionPerformed(evt);
            }
        });

        jLabel4.setText("Pershkrimi:");

        txtpershkrimi.setColumns(20);
        txtpershkrimi.setRows(5);
        jScrollPane1.setViewportView(txtpershkrimi);

        jLabel5.setText("Karakteristika:");

        txtkarakteristika.setColumns(20);
        txtkarakteristika.setRows(5);
        jScrollPane2.setViewportView(txtkarakteristika);

        jLabel6.setText("Pagesa:");

        txtpagesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagesaActionPerformed(evt);
            }
        });

        jLabel7.setText("Dhoma e zene:");

        cbodhoma_e_zene.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "disponibel", "e zene", "e lire" }));
        cbodhoma_e_zene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodhoma_e_zeneActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipi dhomave:");

        cbotipi_dhomave.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Individuale", "Familjare", "Martesore", "Presidenciale" }));
        cbotipi_dhomave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipi_dhomaveActionPerformed(evt);
            }
        });

        btne_re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/e re.GIF"))); // NOI18N
        btne_re.setText("e re");
        btne_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne_reActionPerformed(evt);
            }
        });

        btnruaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/ruaj.png"))); // NOI18N
        btnruaj.setText("ruaj");
        btnruaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnruajActionPerformed(evt);
            }
        });

        btnkancelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kancelo.png"))); // NOI18N
        btnkancelo.setText("kancelo");
        btnkancelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkanceloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnruaj)
                        .addGap(66, 66, 66)
                        .addComponent(btnkancelo)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(49, 49, 49)
                .addComponent(cbotipi_dhomave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btne_re)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtiddhoma, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbopersonat, javax.swing.GroupLayout.Alignment.LEADING, 0, 99, Short.MAX_VALUE)
                        .addComponent(txtnumri, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbodhoma_e_zene, javax.swing.GroupLayout.Alignment.LEADING, 0, 114, Short.MAX_VALUE)
                        .addComponent(txtpagesa, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtiddhoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnumri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cbopersonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpagesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbodhoma_e_zene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbotipi_dhomave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btne_re)
                    .addComponent(btnruaj)
                    .addComponent(btnkancelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista e Dhomave"));

        jLabel9.setText("Kerko");

        txtkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkerkoActionPerformed(evt);
            }
        });

        btnkerko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kerko.png"))); // NOI18N
        btnkerko.setText("kerko");
        btnkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoActionPerformed(evt);
            }
        });

        btnelimino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/elimino.png"))); // NOI18N
        btnelimino.setText("elimino");
        btnelimino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminoActionPerformed(evt);
            }
        });

        btnshtepi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/shtepi.gif"))); // NOI18N
        btnshtepi.setText("shtepi");
        btnshtepi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshtepiActionPerformed(evt);
            }
        });

        listtabele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listtabele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listtabeleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listtabele);

        lbltotalregjister.setText("Regjister");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(61, 61, 61)
                .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkerko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnelimino)
                .addGap(18, 18, 18)
                .addComponent(btnshtepi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalregjister)
                .addGap(61, 61, 61))
            .addComponent(jScrollPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkerko)
                    .addComponent(btnelimino)
                    .addComponent(btnshtepi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbltotalregjister)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumriActionPerformed
        // TODO add your handling code here:
        txtnumri.transferFocus();
    }//GEN-LAST:event_txtnumriActionPerformed

    private void btne_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne_reActionPerformed
        // TODO add your handling code here:
         avantazh();
        btnruaj.setText("ruaj");
        accion = "ruaj";


    }//GEN-LAST:event_btne_reActionPerformed

    private void btnruajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnruajActionPerformed
        // TODO add your handling code here:
          if (txtnumri.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ju lutem jepni numrin e dhomave");
            txtnumri.requestFocus();
            return;
            
        }
         
          
        if (txtpershkrimi.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ju lutem jepni pershkrimin e dhomes");
            txtpershkrimi.requestFocus();
            return;
        }

        if (txtpagesa.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ju lutem shenoni pagesen e dhomes");
            txtpagesa.requestFocus();
            return;
        }

        if (txtkarakteristika.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ju lutem shkruani karakteristikat e dhomes");
            txtkarakteristika.requestFocus();
            return;
        }

        vdhoma dts = new vdhoma();
        fdhoma func = new fdhoma();

        dts.setNumri(txtnumri.getText());

        int seleccionado = cbodhoma_e_zene.getSelectedIndex();
        dts.setDhoma_e_zene((String) cbodhoma_e_zene.getItemAt(seleccionado));
        
    
        dts.setPershkrimi(txtpershkrimi.getText());
        dts.setKarakteristika(txtkarakteristika.getText());
        
      seleccionado=cbopersonat.getSelectedIndex();
      dts.setPersonat((String)cbopersonat.getItemAt(seleccionado));
        
        dts.setPagesa(Double.parseDouble(txtpagesa.getText()));
        
        seleccionado = cbodhoma_e_zene.getSelectedIndex();
        dts.setDhoma_e_zene((String) cbodhoma_e_zene.getItemAt(seleccionado));
        
        seleccionado = cbotipi_dhomave.getSelectedIndex();
        dts.setTipi_dhomave((String) cbotipi_dhomave.getItemAt(seleccionado));
        
        
        if (accion.equals("ruaj")) {
            if (func.shto(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Dhoma u regjistrua me sukses");
                moster("");
               inavantazh();
                
            }
            
            
            
            
        }
        else if (accion.equals("shkruaj")){
            dts.setIddhoma(Integer.parseInt(txtiddhoma.getText()));
            
            
            if (func.shkruaj(dts)) {
                JOptionPane.showMessageDialog(rootPane, "dhoma u shkrua me sukses");
                moster("");
                inavantazh();
            }
        }
        
        
        

    }//GEN-LAST:event_btnruajActionPerformed

    private void btnkanceloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkanceloActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnkanceloActionPerformed

    private void txtkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkerkoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkerkoActionPerformed

    private void btnkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoActionPerformed
        // TODO add your handling code here:
           moster(txtkerko.getText());
    }//GEN-LAST:event_btnkerkoActionPerformed

    private void btneliminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminoActionPerformed
        // TODO add your handling code here:
          if (!txtiddhoma.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "ne qofte se doni ta eliminoni kete dhome?","konfirmoje",2);
            
            if (confirmacion==0) {
                fdhoma func = new fdhoma ();
                vdhoma dts= new vdhoma();
                
                dts.setIddhoma(Integer.parseInt(txtiddhoma.getText()));
                func.elimino(dts);
                moster("");
                inavantazh();
                
            }
            
            
        }
    }//GEN-LAST:event_btneliminoActionPerformed

    private void btnshtepiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshtepiActionPerformed
        // TODO add your handling code here:
         this.dispose();
        
    }//GEN-LAST:event_btnshtepiActionPerformed

    private void listtabeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listtabeleMouseClicked
        // TODO add your handling code here:
          btnruaj.setText("shkruaj");
        avantazh();
        btnelimino.setEnabled(true);
        accion="shkruaj";
        
        int fila = listtabele.rowAtPoint(evt.getPoint());
        
        txtiddhoma.setText(listtabele.getValueAt(fila, 0).toString());
        txtnumri.setText(listtabele.getValueAt(fila, 1).toString());
        
       cbopersonat.setSelectedItem(listtabele.getValueAt(fila, 2).toString());
       txtpershkrimi.setText(listtabele.getValueAt(fila, 3).toString());
       txtkarakteristika.setText(listtabele.getValueAt(fila, 4).toString());
        txtpagesa.setText(listtabele.getValueAt(fila, 5).toString());
        
        cbodhoma_e_zene.setSelectedItem(listtabele.getValueAt(fila, 6).toString());
        cbotipi_dhomave.setSelectedItem(listtabele.getValueAt(fila, 7).toString());
        
       
    }//GEN-LAST:event_listtabeleMouseClicked

    private void cbotipi_dhomaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipi_dhomaveActionPerformed
        // TODO add your handling code here:
        transferFocus();
    }//GEN-LAST:event_cbotipi_dhomaveActionPerformed

    private void cbodhoma_e_zeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodhoma_e_zeneActionPerformed
        // TODO add your handling code here:
        cbodhoma_e_zene.transferFocus();
    }//GEN-LAST:event_cbodhoma_e_zeneActionPerformed

    private void txtpagesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagesaActionPerformed
        // TODO add your handling code here:
        txtpagesa.transferFocus();
    }//GEN-LAST:event_txtpagesaActionPerformed

    private void cbopersonatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopersonatActionPerformed
        // TODO add your handling code here:
        cbopersonat.transferFocus();
    }//GEN-LAST:event_cbopersonatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmdhoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btne_re;
    private javax.swing.JButton btnelimino;
    private javax.swing.JButton btnkancelo;
    private javax.swing.JButton btnkerko;
    private javax.swing.JButton btnruaj;
    private javax.swing.JButton btnshtepi;
    private javax.swing.JComboBox cbodhoma_e_zene;
    private javax.swing.JComboBox cbopersonat;
    private javax.swing.JComboBox cbotipi_dhomave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbltotalregjister;
    private javax.swing.JTable listtabele;
    private javax.swing.JTextField txtiddhoma;
    private javax.swing.JTextArea txtkarakteristika;
    private javax.swing.JTextField txtkerko;
    private javax.swing.JTextField txtnumri;
    private javax.swing.JTextField txtpagesa;
    private javax.swing.JTextArea txtpershkrimi;
    // End of variables declaration//GEN-END:variables
}
