/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prezantimi;

import data.vkonsumatori;
import login.fkonsumatori;
import login.fprodukti;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geraldo
 */
public class frmkonsumatori extends javax.swing.JInternalFrame {
public static String idrezervimi;
public static String klienti;
    
        
    /**
     * Creates new form frmConsumo
     */
    public frmkonsumatori() {
        initComponents();
        moster(idrezervimi);
        txtklienti.setText(klienti);
        txtidrezervimi.setText(idrezervimi);
        inavantazh();
        
    }
     private String accion = "ruaj";

    void fshehje_kolone() {
        listtabele.getColumnModel().getColumn(0).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(0).setMinWidth(0);
        listtabele.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        listtabele.getColumnModel().getColumn(1).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(1).setMinWidth(0);
        listtabele.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        listtabele.getColumnModel().getColumn(2).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(2).setMinWidth(0);
        listtabele.getColumnModel().getColumn(2).setPreferredWidth(0);
    }

    void inavantazh() {
        txtidkonsumatori.setVisible(false);
        
        txtidrezervimi.setVisible(false);
        txtklienti.setEnabled(false);
        txtidprodukti.setVisible(false);
        txtprodukti.setEnabled(false);
        txtkandidate.setEnabled(false);
                
        txtulje_cemimi.setEnabled(false);
        cbodhoma_e_zene.setEnabled(false);
        

        btnruaj.setEnabled(false);
        btnkancelo.setEnabled(false);
        btnelimino.setEnabled(false);
        
        txtidkonsumatori.setText("");
        txtulje_cemimi.setText("");
        txtidprodukti.setText("");
        txtprodukti.setText("");
        txtkandidate.setText("");

    }

    void avantazh() {
        txtidkonsumatori.setVisible(false);
        
        txtidrezervimi.setVisible(false);
        txtklienti.setEnabled(true);
        txtidprodukti.setVisible(false);
        txtprodukti.setEnabled(true);
        txtkandidate.setEnabled(true);
                
        txtulje_cemimi.setEnabled(true);
        cbodhoma_e_zene.setEnabled(true);
        

        btnruaj.setEnabled(true);
        btnkancelo.setEnabled(true);
        btnelimino.setEnabled(true);
        
        txtidkonsumatori.setText("");
        txtulje_cemimi.setText("");
        txtidprodukti.setText("");
        txtprodukti.setText("");
        txtkandidate.setText("");

    }

    void moster(String kerko) {
        try {
            DefaultTableModel model;
            fkonsumatori func = new fkonsumatori();
            model = func.moster(kerko);

            listtabele.setModel(model);
            fshehje_kolone();
            lbltotalregjister.setText("Total Regjister " + Integer.toString(func.totalregjister));
            lblkonsumatori.setText("konsumi total $. " + func.totalkonsumatori);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtidkonsumatori = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtidrezervimi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtulje_cemimi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbodhoma_e_zene = new javax.swing.JComboBox();
        btne_re = new javax.swing.JButton();
        btnruaj = new javax.swing.JButton();
        btnkancelo = new javax.swing.JButton();
        txtklienti = new javax.swing.JTextField();
        txtidprodukti = new javax.swing.JTextField();
        txtprodukti = new javax.swing.JTextField();
        btnkerkoprodukti = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtkandidate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listtabele = new javax.swing.JTable();
        btnelimino = new javax.swing.JButton();
        btnshtepi = new javax.swing.JButton();
        lbltotalregjister = new javax.swing.JLabel();
        lblkonsumatori = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Regjistrimi konsumatorit"));

        jLabel2.setText("Rezervimi:");

        txtidrezervimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidrezervimiActionPerformed(evt);
            }
        });

        jLabel4.setText("Produkti:");

        jLabel6.setText("ulje cemimi:");

        txtulje_cemimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtulje_cemimiActionPerformed(evt);
            }
        });

        jLabel7.setText("Dhoma:");

        cbodhoma_e_zene.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prano", "kancelo" }));
        cbodhoma_e_zene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodhoma_e_zeneActionPerformed(evt);
            }
        });

        btne_re.setBackground(new java.awt.Color(51, 51, 51));
        btne_re.setForeground(new java.awt.Color(255, 255, 255));
        btne_re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/e re.GIF"))); // NOI18N
        btne_re.setText("e re");
        btne_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne_reActionPerformed(evt);
            }
        });

        btnruaj.setBackground(new java.awt.Color(51, 51, 51));
        btnruaj.setForeground(new java.awt.Color(255, 255, 255));
        btnruaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/ruaj.png"))); // NOI18N
        btnruaj.setText("ruaj");
        btnruaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnruajActionPerformed(evt);
            }
        });

        btnkancelo.setBackground(new java.awt.Color(51, 51, 51));
        btnkancelo.setForeground(new java.awt.Color(255, 255, 255));
        btnkancelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kancelo.png"))); // NOI18N
        btnkancelo.setText("kancelo");
        btnkancelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkanceloActionPerformed(evt);
            }
        });

        txtklienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtklientiActionPerformed(evt);
            }
        });

        txtidprodukti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidproduktiActionPerformed(evt);
            }
        });

        btnkerkoprodukti.setText("...");
        btnkerkoprodukti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoproduktiActionPerformed(evt);
            }
        });

        jLabel5.setText("kandidate:");

        txtkandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkandidateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtidkonsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btne_re)
                        .addGap(42, 42, 42)
                        .addComponent(btnruaj)
                        .addGap(58, 58, 58)
                        .addComponent(btnkancelo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(53, 53, 53)
                                .addComponent(txtidrezervimi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtklienti, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtkandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtidprodukti, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(txtprodukti, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(61, 61, 61)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbodhoma_e_zene, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtulje_cemimi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnkerkoprodukti, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtidkonsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidrezervimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtklienti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtidprodukti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprodukti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkerkoprodukti))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtkandidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtulje_cemimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbodhoma_e_zene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btne_re)
                    .addComponent(btnruaj)
                    .addComponent(btnkancelo))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("konsumatori");
        jLabel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista e konsumatorit"));

        listtabele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listtabele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listtabeleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listtabele);

        btnelimino.setBackground(new java.awt.Color(51, 51, 51));
        btnelimino.setForeground(new java.awt.Color(255, 255, 255));
        btnelimino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/elimino.png"))); // NOI18N
        btnelimino.setText("elimino");
        btnelimino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminoActionPerformed(evt);
            }
        });

        btnshtepi.setBackground(new java.awt.Color(51, 51, 51));
        btnshtepi.setForeground(new java.awt.Color(255, 255, 255));
        btnshtepi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/shtepi.gif"))); // NOI18N
        btnshtepi.setText("shtepi");
        btnshtepi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshtepiActionPerformed(evt);
            }
        });

        lbltotalregjister.setText("regjistri");

        lblkonsumatori.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnelimino)
                                .addGap(18, 18, 18)
                                .addComponent(btnshtepi))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblkonsumatori)
                                .addGap(54, 54, 54)
                                .addComponent(lbltotalregjister, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnelimino)
                    .addComponent(btnshtepi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotalregjister)
                    .addComponent(lblkonsumatori)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidrezervimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidrezervimiActionPerformed
        // TODO add your handling code here:
        txtidrezervimi.transferFocus();
    }//GEN-LAST:event_txtidrezervimiActionPerformed

    private void txtulje_cemimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtulje_cemimiActionPerformed
        // TODO add your handling code here:
        txtulje_cemimi.transferFocus();
    }//GEN-LAST:event_txtulje_cemimiActionPerformed

    private void cbodhoma_e_zeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodhoma_e_zeneActionPerformed
        // TODO add your handling code here:
        cbodhoma_e_zene.transferFocus();
    }//GEN-LAST:event_cbodhoma_e_zeneActionPerformed

    private void btne_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne_reActionPerformed
        // TODO add your handling code here:
        avantazh();
        btnruaj.setText("ruaj");
        accion = "ruaj";
    }//GEN-LAST:event_btne_reActionPerformed

    private void btnruajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnruajActionPerformed
        // TODO add your handling code here:
        if (txtidprodukti.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "jep seleksionimin e produktit");
            btnkerkoprodukti.requestFocus();
            return;
        }
        if (txtkandidate.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "jepni kandidatin e konsumatorit");
            txtkandidate.requestFocus();
            return;
        }

        if (txtulje_cemimi.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "jepni uljet e cemimit per konsumatorin");
            txtulje_cemimi.requestFocus();
            return;
        }

        vkonsumatori dts = new vkonsumatori();
        fkonsumatori func = new fkonsumatori();

        dts.setIdrezervimi(Integer.parseInt(txtidrezervimi.getText()));
        dts.setIdprodukti(Integer.parseInt(txtidprodukti.getText()));
        dts.setKandidate(Double.parseDouble(txtkandidate.getText()));
        dts.setUlje_cemimi(Double.parseDouble(txtulje_cemimi.getText()));
        
        int seleccionado = cbodhoma_e_zene.getSelectedIndex();
        dts.setDhoma_e_zene((String) cbodhoma_e_zene.getItemAt(seleccionado));

        if (accion.equals("ruaj")) {
            if (func.shto(dts)) {
                JOptionPane.showMessageDialog(rootPane, "konsumatori " + txtprodukti.getText() + " klienti "
                        + txtklienti.getText() + " u regjistrua me sukses");
                moster(idrezervimi);
                inavantazh();

            }

        }
        else if (accion.equals("shkruaj")){
            dts.setIdkonsumatori(Integer.parseInt(txtidkonsumatori.getText()));

            if (func.shkruaj(dts)) {
                JOptionPane.showMessageDialog(rootPane, "konsumi i klientit "
                        + txtklienti.getText() + " u modifikua me sukses ");
                moster(idrezervimi);
                inavantazh();
            }
        }
    }//GEN-LAST:event_btnruajActionPerformed

    private void btnkanceloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkanceloActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnkanceloActionPerformed

    private void listtabeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listtabeleMouseClicked
        // TODO add your handling code here:
        btnruaj.setText("shkruaj");
        avantazh();
        btnelimino.setEnabled(true);
        accion="shkruaj";

        int fila = listtabele.rowAtPoint(evt.getPoint());

        txtidkonsumatori.setText(listtabele.getValueAt(fila, 0).toString());
        txtidrezervimi.setText(listtabele.getValueAt(fila, 1).toString());
           txtklienti.setText(listtabele.getValueAt(fila, 2).toString());
        txtidprodukti.setText(listtabele.getValueAt(fila, 3).toString());
        txtprodukti.setText(listtabele.getValueAt(fila, 4).toString());
        txtkandidate.setText(listtabele.getValueAt(fila, 5).toString());
        txtulje_cemimi.setText(listtabele.getValueAt(fila, 6).toString());
        
        cbodhoma_e_zene.setSelectedItem(listtabele.getValueAt(fila, 7).toString());
        

    }//GEN-LAST:event_listtabeleMouseClicked

    private void btneliminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminoActionPerformed
        // TODO add your handling code here:
        if (!txtidkonsumatori.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "a je i sigurt qe do te fshish kete produkt?","konfirmo",2);

            if (confirmacion==0) {
                fkonsumatori func = new fkonsumatori ();
                vkonsumatori dts= new vkonsumatori();

                dts.setIdkonsumatori(Integer.parseInt(txtidkonsumatori.getText()));
                func.elimino(dts);
                moster(idrezervimi);
                inavantazh();

            }

        }
    }//GEN-LAST:event_btneliminoActionPerformed

    private void btnshtepiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshtepiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnshtepiActionPerformed

    private void txtidproduktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidproduktiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidproduktiActionPerformed

    private void txtkandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkandidateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkandidateActionPerformed

    private void btnkerkoproduktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoproduktiActionPerformed
        // TODO add your handling code here:
        frmvizitprodukti form = new frmvizitprodukti();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnkerkoproduktiActionPerformed

    private void txtklientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtklientiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtklientiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmkonsumatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmkonsumatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmkonsumatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmkonsumatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmkonsumatori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btne_re;
    private javax.swing.JButton btnelimino;
    private javax.swing.JButton btnkancelo;
    private javax.swing.JButton btnkerkoprodukti;
    private javax.swing.JButton btnruaj;
    private javax.swing.JButton btnshtepi;
    private javax.swing.JComboBox cbodhoma_e_zene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblkonsumatori;
    private javax.swing.JLabel lbltotalregjister;
    private javax.swing.JTable listtabele;
    private javax.swing.JTextField txtidkonsumatori;
    public static javax.swing.JTextField txtidprodukti;
    private javax.swing.JTextField txtidrezervimi;
    private javax.swing.JTextField txtkandidate;
    private javax.swing.JTextField txtklienti;
    public static javax.swing.JTextField txtprodukti;
    public static javax.swing.JTextField txtulje_cemimi;
    // End of variables declaration//GEN-END:variables
}
