/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prezantimi;
import data.vrezervimi;
import login.fprodukti;
import login.frezervimi;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author geraldo
 */
public class frmpamja extends javax.swing.JFrame {

    /**
     * Creates new form frminicio
     */
    public frmpamja() {
        initComponents();
      this.setExtendedState(frmpamja.MAXIMIZED_BOTH);
        this.setTitle("Sistemi i rezervimit te hotelit - HOTEL ADRIATIK ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pamjet = new javax.swing.JDesktopPane();
        lblidpersoni = new javax.swing.JLabel();
        lblemri = new javax.swing.JLabel();
        lblatesia = new javax.swing.JLabel();
        lblamesia = new javax.swing.JLabel();
        lblaksesi = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnusisrezervimi = new javax.swing.JMenu();
        mnuarkiva = new javax.swing.JMenu();
        copyMenuItem = new javax.swing.JMenuItem();
        cutMenuItem = new javax.swing.JMenuItem();
        mnurezervimi = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        frmklienti = new javax.swing.JMenuItem();
        mnukonfigurim = new javax.swing.JMenu();
        frmuserlogin = new javax.swing.JMenuItem();
        mnudalje = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pamjet.setBackground(new java.awt.Color(102, 255, 255));

        lblidpersoni.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblidpersoni.setText("jLabel1");
        pamjet.add(lblidpersoni);
        lblidpersoni.setBounds(20, 10, 130, 16);

        lblemri.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblemri.setText("jLabel2");
        pamjet.add(lblemri);
        lblemri.setBounds(20, 40, 130, 16);

        lblatesia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblatesia.setText("jLabel3");
        pamjet.add(lblatesia);
        lblatesia.setBounds(20, 70, 130, 16);

        lblamesia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblamesia.setText("jLabel4");
        pamjet.add(lblamesia);
        lblamesia.setBounds(20, 110, 130, 16);

        lblaksesi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblaksesi.setText("jLabel7");
        pamjet.add(lblaksesi);
        lblaksesi.setBounds(20, 140, 130, 16);

        mnusisrezervimi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/hyrje.png"))); // NOI18N
        mnusisrezervimi.setMnemonic('f');
        mnusisrezervimi.setText("Sisrezervimi");
        menuBar.add(mnusisrezervimi);

        mnuarkiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/Arkiva.png"))); // NOI18N
        mnuarkiva.setMnemonic('e');
        mnuarkiva.setText("Arkiva");

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/produkti.png"))); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("produkti");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        mnuarkiva.add(copyMenuItem);

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/dhoma.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("dhoma");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        mnuarkiva.add(cutMenuItem);

        menuBar.add(mnuarkiva);

        mnurezervimi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/Rezervimi.png"))); // NOI18N
        mnurezervimi.setMnemonic('h');
        mnurezervimi.setText("Rezervimi");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/rezervimi-konsumi.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Rezervimi  & konsumimi");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        mnurezervimi.add(contentMenuItem);

        frmklienti.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        frmklienti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/klienti.png"))); // NOI18N
        frmklienti.setMnemonic('a');
        frmklienti.setText("klienti");
        frmklienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmklientiActionPerformed(evt);
            }
        });
        mnurezervimi.add(frmklienti);

        menuBar.add(mnurezervimi);

        mnukonfigurim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/konfiguro.png"))); // NOI18N
        mnukonfigurim.setText("konfigurimi");

        frmuserlogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        frmuserlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/punonjes.png"))); // NOI18N
        frmuserlogin.setText("User dhe Akses");
        frmuserlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmuserloginActionPerformed(evt);
            }
        });
        mnukonfigurim.add(frmuserlogin);

        menuBar.add(mnukonfigurim);

        mnudalje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/Shtepi.png"))); // NOI18N
        mnudalje.setText("Dalje");
        mnudalje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnudaljeMouseClicked(evt);
            }
        });
        menuBar.add(mnudalje);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pamjet, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pamjet, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        frmdhoma form =new frmdhoma();
        pamjet.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        frmprodukti form =new frmprodukti();
        pamjet.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void frmklientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmklientiActionPerformed
        // TODO add your handling code here:
        frmklienti form =new frmklienti();
        pamjet.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_frmklientiActionPerformed

    private void mnudaljeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnudaljeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnudaljeMouseClicked

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
       frmrezervimi form = new frmrezervimi();
        pamjet.add(form);
        form.toFront();
        form.setVisible(true);
        frmrezervimi.txtidpunonjes.setText(lblidpersoni.getText());
        frmrezervimi.txtpunonjes.setText(lblemri.getText() + "  " + lblatesia.getText());
        frmrezervimi.iduser=Integer.parseInt(lblidpersoni.getText());
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void frmuserloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmuserloginActionPerformed
        // TODO add your handling code here:
        frmpunonjes form =new frmpunonjes();
        pamjet.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_frmuserloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpamja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpamja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpamja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpamja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpamja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem frmklienti;
    private javax.swing.JMenuItem frmuserlogin;
    public static javax.swing.JLabel lblaksesi;
    public static javax.swing.JLabel lblamesia;
    public static javax.swing.JLabel lblatesia;
    public static javax.swing.JLabel lblemri;
    public static javax.swing.JLabel lblidpersoni;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu mnuarkiva;
    private javax.swing.JMenu mnudalje;
    public static javax.swing.JMenu mnukonfigurim;
    private javax.swing.JMenu mnurezervimi;
    private javax.swing.JMenu mnusisrezervimi;
    public static javax.swing.JDesktopPane pamjet;
    // End of variables declaration//GEN-END:variables

}
