/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prezantimi;

import data.vprodukti;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.fdhoma;
import login.fprodukti;

/**
 *
 * @autor geraldo
 */
public class frmprodukti extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmprodukti
     */
    public frmprodukti() {
        initComponents();
        moster("");
        inavantazh();
    }
    
    private String accion = "ruaj";

    void fshehje_kolone() {
        listtabele.getColumnModel().getColumn(0).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(0).setMinWidth(0);
        listtabele.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    void inavantazh() {
        txtidprodukti.setVisible(false);
        txtemri.setEnabled(false);
        txtpershkrim.setEnabled(false);
        cbosasi.setEnabled(false);
       txtulje_cemimi.setEnabled(false);

        btnruaj.setEnabled(false);
        btnkancelo.setEnabled(false);
        btnelimino.setEnabled(false);
        txtidprodukti.setText("");
        txtulje_cemimi.setText("");
        txtemri.setText("");
        txtpershkrim.setText("");

    }

    void avantazh() {
        txtidprodukti.setVisible(false);

        cbosasi.setEnabled(true);
        txtemri.setEnabled(true);
        txtpershkrim.setEnabled(true);
        txtulje_cemimi.setEnabled(true);
       

        btnruaj.setEnabled(true);
        btnkancelo.setEnabled(true);
        btnelimino.setEnabled(true);
        txtidprodukti.setText("");
        txtulje_cemimi.setText("");
        txtemri.setText("");
        txtpershkrim.setText("");

    }

    void moster(String kerko) {
        try {
            DefaultTableModel model;
            fprodukti func = new fprodukti();
            model = func.moster(kerko);

            listtabele.setModel(model);
            fshehje_kolone();
            lbltotalregjister.setText("Total Regjister " + Integer.toString(func.totalregjister));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtkerko = new javax.swing.JTextField();
        btnkerko = new javax.swing.JButton();
        btnelimino = new javax.swing.JButton();
        btnshtepi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listtabele = new javax.swing.JTable();
        lbltotalregjister = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtidprodukti = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpershkrim = new javax.swing.JTextArea();
        txtulje_cemimi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbosasi = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        btne_re = new javax.swing.JButton();
        btnruaj = new javax.swing.JButton();
        btnkancelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista e produkteve"));

        jLabel9.setText("Kerko");

        txtkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkerkoActionPerformed(evt);
            }
        });

        btnkerko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kerko.png"))); // NOI18N
        btnkerko.setText("kerko");
        btnkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoActionPerformed(evt);
            }
        });

        btnelimino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/elimino.png"))); // NOI18N
        btnelimino.setText("elimino");
        btnelimino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminoActionPerformed(evt);
            }
        });

        btnshtepi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/shtepi.gif"))); // NOI18N
        btnshtepi.setText("shtepi");
        btnshtepi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshtepiActionPerformed(evt);
            }
        });

        listtabele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listtabele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listtabeleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listtabele);

        lbltotalregjister.setText("Regjister");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(61, 61, 61)
                        .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnkerko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnelimino)
                        .addGap(18, 18, 18)
                        .addComponent(btnshtepi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalregjister)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkerko)
                    .addComponent(btnelimino)
                    .addComponent(btnshtepi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbltotalregjister)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Regjistri i produkteve"));

        jLabel2.setText("Emri:");

        txtemri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemriActionPerformed(evt);
            }
        });

        jLabel4.setText("Pershkrim:");

        txtpershkrim.setColumns(20);
        txtpershkrim.setRows(5);
        jScrollPane1.setViewportView(txtpershkrim);

        txtulje_cemimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtulje_cemimiActionPerformed(evt);
            }
        });

        jLabel7.setText("Sasi:");

        cbosasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kg", "cop", "lit", "meter", " " }));
        cbosasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbosasiActionPerformed(evt);
            }
        });

        jLabel8.setText("Ulje Cemimi:");

        btne_re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/e re.GIF"))); // NOI18N
        btne_re.setText("e re");
        btne_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne_reActionPerformed(evt);
            }
        });

        btnruaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/ruaj.png"))); // NOI18N
        btnruaj.setText("ruaj");
        btnruaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnruajActionPerformed(evt);
            }
        });

        btnkancelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kancelo.png"))); // NOI18N
        btnkancelo.setText("kancelo");
        btnkancelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkanceloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btne_re)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtulje_cemimi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(btnruaj)
                        .addGap(66, 66, 66)
                        .addComponent(btnkancelo)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                            .addComponent(txtemri)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbosasi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtidprodukti, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtidprodukti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbosasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtulje_cemimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btne_re)
                    .addComponent(btnruaj)
                    .addComponent(btnkancelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Produkti");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkerkoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkerkoActionPerformed

    private void btnkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoActionPerformed
        // TODO add your handling code here:
        moster(txtkerko.getText());
    }//GEN-LAST:event_btnkerkoActionPerformed

    private void btneliminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminoActionPerformed
        // TODO add your handling code here:
        if (!txtidprodukti.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "ne qofte se doni ta eliminoni kete produkt?","konfirmoje",2);

            if (confirmacion==0) {
                fprodukti func = new fprodukti ();
                vprodukti dts= new vprodukti();

                dts.setIdprodukti(Integer.parseInt(txtidprodukti.getText()));
                func.elimino(dts);
                moster("");
                inavantazh();

            }

        }
    }//GEN-LAST:event_btneliminoActionPerformed

    private void btnshtepiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshtepiActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnshtepiActionPerformed

    private void listtabeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listtabeleMouseClicked
        // TODO add your handling code here:
        btnruaj.setText("ruaj");
        avantazh();
        btnelimino.setEnabled(true);
        accion="ruaj";

        int fila = listtabele.rowAtPoint(evt.getPoint());

        txtidprodukti.setText(listtabele.getValueAt(fila, 0).toString());
        txtemri.setText(listtabele.getValueAt(fila, 1).toString());
        txtulje_cemimi.setText(listtabele.getValueAt(fila, 2).toString());
        cbosasi.setSelectedItem(listtabele.getValueAt(fila, 3).toString());
        

    }//GEN-LAST:event_listtabeleMouseClicked

    private void txtemriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemriActionPerformed
        // TODO add your handling code here:
        txtemri.transferFocus();
    }//GEN-LAST:event_txtemriActionPerformed

    private void txtulje_cemimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtulje_cemimiActionPerformed
        // TODO add your handling code here:
        txtulje_cemimi.transferFocus();
    }//GEN-LAST:event_txtulje_cemimiActionPerformed

    private void cbosasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbosasiActionPerformed
        // TODO add your handling code here:
        cbosasi.transferFocus();
    }//GEN-LAST:event_cbosasiActionPerformed

    private void btne_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne_reActionPerformed
        // TODO add your handling code here:
        avantazh();
        btnruaj.setText("ruaj");
        accion = "ruaj";

    }//GEN-LAST:event_btne_reActionPerformed

    private void btnruajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnruajActionPerformed
        // TODO add your handling code here:
        if (txtemri.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ju lutem jepni emrin e produktit");
            txtemri.requestFocus();
            return;

        }

        if (txtpershkrim.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ju lutem jepni pershkrimin e produktit");
            txtpershkrim.requestFocus();
            return;
        }

        if (txtulje_cemimi.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Ju lutem jepni uljet e cemimit");
            txtulje_cemimi.requestFocus();
            return;
        }

       
        

        vprodukti dts = new vprodukti();
        fprodukti func = new fprodukti();

        dts.setEmri(txtemri.getText());

        int seleccionado = cbosasi.getSelectedIndex();
        dts.setSasi((String) cbosasi.getItemAt(seleccionado));

        dts.setPershkrim(txtpershkrim.getText());
 
       dts.setUlje_cemimi(Double.parseDouble(txtulje_cemimi.getText()));
 
      
        if (accion.equals("ruaj")) {
            if (func.shto(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Produkti u regjistrua me sukses");
                moster("");
                inavantazh();

            }

        }
        else if (accion.equals("shkruaj")){
            dts.setIdprodukti(Integer.parseInt(txtidprodukti.getText()));

            if (func.shkruaj(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Produkti u shkrua me sukses");
                moster("");
                inavantazh();
            }
        }

    }//GEN-LAST:event_btnruajActionPerformed

    private void btnkanceloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkanceloActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnkanceloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprodukti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprodukti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprodukti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprodukti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprodukti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btne_re;
    private javax.swing.JButton btnelimino;
    private javax.swing.JButton btnkancelo;
    private javax.swing.JButton btnkerko;
    private javax.swing.JButton btnruaj;
    private javax.swing.JButton btnshtepi;
    private javax.swing.JComboBox cbosasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbltotalregjister;
    private javax.swing.JTable listtabele;
    private javax.swing.JTextField txtemri;
    private javax.swing.JTextField txtidprodukti;
    private javax.swing.JTextField txtkerko;
    private javax.swing.JTextArea txtpershkrim;
    private javax.swing.JTextField txtulje_cemimi;
    // End of variables declaration//GEN-END:variables
}
