/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prezantimi;

import data.vdhoma;
import data.vrezervimi;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.fdhoma;
import login.frezervimi;
import login.fprodukti;
/**
 *
 * @autor geraldo
 */
public class frmrezervimi extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmrezervimi
     */
    public frmrezervimi() {
        initComponents();
         moster("");
        inavantazh();
    }
private String accion = "ruaj";
     public static int iduser;
    void fshehje_kolone() {
        listtabele.getColumnModel().getColumn(0).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(0).setMinWidth(0);
        listtabele.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        listtabele.getColumnModel().getColumn(1).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(1).setMinWidth(0);
        listtabele.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        listtabele.getColumnModel().getColumn(3).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(3).setMinWidth(0);
        listtabele.getColumnModel().getColumn(3).setPreferredWidth(0);
        
        listtabele.getColumnModel().getColumn(5).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(5).setMinWidth(0);
        listtabele.getColumnModel().getColumn(5).setPreferredWidth(0);
    }

    void inavantazh() {
        txtidrezervimi.setVisible(false);
        txtiddhoma.setVisible(false);
        txtidklienti.setVisible(false);
        txtidpunonjes.setVisible(false);
        
        txtnumri.setEnabled(false);
        txtklienti.setEnabled(false);
        txtpunonjes.setEnabled(false);
        cbotipi_rezervimit.setEnabled(false);
        
        dcdata_rezervimit.setEnabled(false);
        dcdat_hyrje.setEnabled(false);
        dcdat_dalje.setEnabled(false);
        
        txtkostoja_e_strehimit.setEnabled(false);
        cbotipi_rezervimit.setEnabled(false);
        

        btnruaj.setEnabled(false);
        btnkancelo.setEnabled(false);
        btnelimino.setEnabled(false);
        btnkerkoklienti.setEnabled(false);
        btnkerkodhoma.setEnabled(false);
        
        
        txtidrezervimi.setText("");
        txtidklienti.setText("");
        txtnumri.setText("");
        txtklienti.setText("");
        txtkostoja_e_strehimit.setText("");
        txtiddhoma.setText("");
        

    }

    void avantazh() {
        txtidrezervimi.setVisible(false);
        txtiddhoma.setVisible(false);
        txtidklienti.setVisible(false);
        txtidpunonjes.setVisible(false);
        
        txtnumri.setEnabled(false);
        txtklienti.setEnabled(false);
        txtpunonjes.setEnabled(false);
        
        cbotipi_rezervimit.setEnabled(true);
        
        dcdata_rezervimit.setEnabled(true);
        dcdat_hyrje.setEnabled(true);
        dcdat_dalje.setEnabled(true);
        
        txtkostoja_e_strehimit.setEnabled(true);
        cbotipi_rezervimit.setEnabled(true);
        

        btnruaj.setEnabled(true);
        btnkancelo.setEnabled(true);
        btnelimino.setEnabled(true);
        btnkerkoklienti.setEnabled(true);
        btnkerkodhoma.setEnabled(true);
        
        
        txtidrezervimi.setText("");
        txtidklienti.setText("");
        txtnumri.setText("");
        txtklienti.setText("");
        txtkostoja_e_strehimit.setText("");
        txtiddhoma.setText("");
        

    }

    void moster(String kerko) {
        try {
            DefaultTableModel model;
            frezervimi func = new frezervimi();
            model = func.moster(kerko);

            listtabele.setModel(model);
            fshehje_kolone();
            lbltotalregjister.setText("Total Regjister " + Integer.toString(func.totalregjister));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionContainerFactory1 = new org.jdesktop.swingx.action.ActionContainerFactory();
        jPanel1 = new javax.swing.JPanel();
        txtidrezervimi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtiddhoma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkostoja_e_strehimit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbotipi_rezervimit = new javax.swing.JComboBox();
        btne_re = new javax.swing.JButton();
        btnruaj = new javax.swing.JButton();
        btnkancelo = new javax.swing.JButton();
        txtnumri = new javax.swing.JTextField();
        txtidklienti = new javax.swing.JTextField();
        txtklienti = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtidpunonjes = new javax.swing.JTextField();
        txtpunonjes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbodhoma_e_zene = new javax.swing.JComboBox();
        btnkerkodhoma = new javax.swing.JButton();
        btnkerkoklienti = new javax.swing.JButton();
        dcdata_rezervimit = new com.toedter.calendar.JDateChooser();
        dcdat_hyrje = new com.toedter.calendar.JDateChooser();
        dcdat_dalje = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listtabele = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtkerko = new javax.swing.JTextField();
        btnkerko = new javax.swing.JButton();
        btnelimino = new javax.swing.JButton();
        btnshtepi = new javax.swing.JButton();
        lbltotalregjister = new javax.swing.JLabel();
        btnverkonsumatori = new javax.swing.JButton();
        btnrealizimipages = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Regjistri i rezervimit"));

        jLabel2.setText("Dhoma:");

        txtiddhoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddhomaActionPerformed(evt);
            }
        });

        jLabel4.setText("Klienti:");

        jLabel6.setText("Kostoja:");

        txtkostoja_e_strehimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkostoja_e_strehimitActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipi Rezervimit:");

        cbotipi_rezervimit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rezervuar", "e lire" }));
        cbotipi_rezervimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipi_rezervimitActionPerformed(evt);
            }
        });

        btne_re.setBackground(new java.awt.Color(51, 51, 51));
        btne_re.setForeground(new java.awt.Color(255, 255, 255));
        btne_re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/e re.GIF"))); // NOI18N
        btne_re.setText("e re");
        btne_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btne_reActionPerformed(evt);
            }
        });

        btnruaj.setBackground(new java.awt.Color(51, 51, 51));
        btnruaj.setForeground(new java.awt.Color(255, 255, 255));
        btnruaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/ruaj.png"))); // NOI18N
        btnruaj.setText("ruaj");
        btnruaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnruajActionPerformed(evt);
            }
        });

        btnkancelo.setBackground(new java.awt.Color(51, 51, 51));
        btnkancelo.setForeground(new java.awt.Color(255, 255, 255));
        btnkancelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kancelo.png"))); // NOI18N
        btnkancelo.setText("kancelo");
        btnkancelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkanceloActionPerformed(evt);
            }
        });

        txtnumri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumriActionPerformed(evt);
            }
        });

        txtidklienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidklientiActionPerformed(evt);
            }
        });

        txtklienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtklientiActionPerformed(evt);
            }
        });

        jLabel5.setText("Punonjes:");

        txtidpunonjes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpunonjesActionPerformed(evt);
            }
        });

        txtpunonjes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpunonjesActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Rezervimit:");

        jLabel8.setText("Dat hyrje:");

        jLabel10.setText("Dat dalje:");

        jLabel11.setText("Dhoma e zene:");

        cbodhoma_e_zene.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E lire", "Paguar", "Anulluar" }));
        cbodhoma_e_zene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodhoma_e_zeneActionPerformed(evt);
            }
        });

        btnkerkodhoma.setText("...");
        btnkerkodhoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkodhomaActionPerformed(evt);
            }
        });

        btnkerkoklienti.setText("...");
        btnkerkoklienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoklientiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)
                                .addGap(34, 34, 34)
                                .addComponent(cbodhoma_e_zene, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btne_re)
                                .addGap(42, 42, 42)
                                .addComponent(btnruaj)
                                .addGap(58, 58, 58)
                                .addComponent(btnkancelo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(48, 48, 48))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7))
                                    .addGap(34, 34, 34)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtidpunonjes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtpunonjes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dcdat_dalje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcdat_hyrje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcdata_rezervimit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbotipi_rezervimit, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidklienti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtklienti, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtiddhoma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtnumri, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnkerkodhoma, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnkerkoklienti, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(txtidrezervimi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(93, 93, 93)
                                .addComponent(txtkostoja_e_strehimit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)))
                        .addGap(139, 179, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtidrezervimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtiddhoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkerkodhoma))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidklienti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtklienti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnkerkoklienti))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpunonjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpunonjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbotipi_rezervimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dcdata_rezervimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dcdat_hyrje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcdat_dalje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkostoja_e_strehimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbodhoma_e_zene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btne_re)
                    .addComponent(btnruaj)
                    .addComponent(btnkancelo))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Reserva");

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista e rezervimit"));

        listtabele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listtabele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listtabeleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listtabele);

        jLabel9.setText("kerko");

        btnkerko.setBackground(new java.awt.Color(51, 51, 51));
        btnkerko.setForeground(new java.awt.Color(255, 255, 255));
        btnkerko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kerko.png"))); // NOI18N
        btnkerko.setText("kerko");
        btnkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoActionPerformed(evt);
            }
        });

        btnelimino.setBackground(new java.awt.Color(51, 51, 51));
        btnelimino.setForeground(new java.awt.Color(255, 255, 255));
        btnelimino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/elimino.png"))); // NOI18N
        btnelimino.setText("elimono");
        btnelimino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminoActionPerformed(evt);
            }
        });

        btnshtepi.setBackground(new java.awt.Color(51, 51, 51));
        btnshtepi.setForeground(new java.awt.Color(255, 255, 255));
        btnshtepi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/shtepi.gif"))); // NOI18N
        btnshtepi.setText("shtepi");
        btnshtepi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshtepiActionPerformed(evt);
            }
        });

        lbltotalregjister.setText("Regjister");

        btnverkonsumatori.setText("konsumatori");
        btnverkonsumatori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverkonsumatoriActionPerformed(evt);
            }
        });

        btnrealizimipages.setText("realizimi pageses");
        btnrealizimipages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrealizimipagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnverkonsumatori, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnrealizimipages, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbltotalregjister, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnkerko, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnelimino)
                                .addGap(18, 18, 18)
                                .addComponent(btnshtepi)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkerko)
                    .addComponent(btnelimino)
                    .addComponent(btnshtepi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotalregjister)
                    .addComponent(btnverkonsumatori)
                    .addComponent(btnrealizimipages)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtiddhomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddhomaActionPerformed
        // TODO add your handling code here:
        txtiddhoma.transferFocus();
    }//GEN-LAST:event_txtiddhomaActionPerformed

    private void txtkostoja_e_strehimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkostoja_e_strehimitActionPerformed
        // TODO add your handling code here:
        txtkostoja_e_strehimit.transferFocus();
    }//GEN-LAST:event_txtkostoja_e_strehimitActionPerformed

    private void cbotipi_rezervimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipi_rezervimitActionPerformed
        // TODO add your handling code here:
        cbotipi_rezervimit.transferFocus();
    }//GEN-LAST:event_cbotipi_rezervimitActionPerformed

    private void btne_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btne_reActionPerformed
        // TODO add your handling code here:
        avantazh();
        btnruaj.setText("ruaj");
        accion = "ruaj";
    }//GEN-LAST:event_btne_reActionPerformed

    private void btnruajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnruajActionPerformed
        // TODO add your handling code here:
        if (txtiddhoma.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "jepni seleksionimin e dhomes");
            txtiddhoma.requestFocus();
            return;
        }
        if (txtidklienti.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "jepni seleksionimin e klientit");
            txtidklienti.requestFocus();
            return;
        }

        if (txtkostoja_e_strehimit.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "jepni koston e strehimit");
            txtkostoja_e_strehimit.requestFocus();
            return;
        }

        vrezervimi dts = new vrezervimi();
        frezervimi func = new frezervimi();

        dts.setIddhoma(Integer.parseInt(txtiddhoma.getText()));
        dts.setIdklienti(Integer.parseInt(txtidklienti.getText()));
        dts.setIdpunonjes(iduser);

        int seleccionado = cbotipi_rezervimit.getSelectedIndex();
        dts.setTipi_rezervimit((String) cbotipi_rezervimit.getItemAt(seleccionado));

        Calendar cal;
        int d,m,a;
        cal=dcdata_rezervimit.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        dts.setData_rezervimit(new Date(a,m,d));

        cal=dcdat_hyrje.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        dts.setDat_hyrje(new Date(a,m,d));

        cal=dcdat_dalje.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        dts.setDat_dalje(new Date(a,m,d));

        dts.setKostoja_e_strehimit(Double.parseDouble(txtkostoja_e_strehimit.getText()));
        seleccionado = cbodhoma_e_zene.getSelectedIndex();
        dts.setDhoma_e_zene((String) cbodhoma_e_zene.getItemAt(seleccionado));

        if (accion.equals("ruaj")) {
            if (func.shto(dts)) {
                JOptionPane.showMessageDialog(rootPane, "rezervimi u rregjistrua me sukses");
                moster("");
                inavantazh();

                //ocupamos la Habitación alquilada
                fdhoma func3= new fdhoma();
                vdhoma dts3 = new vdhoma();

                dts3.setIddhoma(Integer.parseInt(txtiddhoma.getText()));
                func3.zene(dts3);
            }

        }
        else if (accion.equals("shkruaj")){
            dts.setIdrezervimi(Integer.parseInt(txtidrezervimi.getText()));
            dts.setIdpunonjes(Integer.parseInt(txtidpunonjes.getText()));
            if (func.shkruaj(dts)) {
                JOptionPane.showMessageDialog(rootPane, "rezervimi u shkrua me sukses");
                moster("");
                inavantazh();
            }
        }
    }//GEN-LAST:event_btnruajActionPerformed

    private void btnkanceloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkanceloActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnkanceloActionPerformed

    private void txtnumriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumriActionPerformed

    private void txtidklientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidklientiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidklientiActionPerformed

    private void txtklientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtklientiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtklientiActionPerformed

    private void txtidpunonjesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpunonjesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpunonjesActionPerformed

    private void txtpunonjesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpunonjesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpunonjesActionPerformed

    private void cbodhoma_e_zeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodhoma_e_zeneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbodhoma_e_zeneActionPerformed

    private void btnkerkodhomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkodhomaActionPerformed
        // TODO add your handling code here:
        frmvizitdhoma form = new frmvizitdhoma();
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_btnkerkodhomaActionPerformed

    private void btnkerkoklientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoklientiActionPerformed
        // TODO add your handling code here:
        frmvizitklienti form= new frmvizitklienti();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnkerkoklientiActionPerformed

    private void listtabeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listtabeleMouseClicked
        // TODO add your handling code here:
        btnruaj.setText("shkruaj");
        avantazh();
        btnelimino.setEnabled(true);
        accion="shkruaj";

        int fila = listtabele.rowAtPoint(evt.getPoint());

        txtidrezervimi.setText(listtabele.getValueAt(fila, 0).toString());
        txtiddhoma.setText(listtabele.getValueAt(fila, 1).toString());
        txtnumri.setText(listtabele.getValueAt(fila, 2).toString());
        txtidklienti.setText(listtabele.getValueAt(fila, 3).toString());
        txtklienti.setText(listtabele.getValueAt(fila, 4).toString());
        txtidpunonjes.setText(listtabele.getValueAt(fila, 5).toString());
        txtpunonjes.setText(listtabele.getValueAt(fila, 6).toString());

        cbotipi_rezervimit.setSelectedItem(listtabele.getValueAt(fila, 7).toString());
        dcdata_rezervimit.setDate(Date.valueOf(listtabele.getValueAt(fila, 8).toString()));
        dcdat_hyrje.setDate(Date.valueOf(listtabele.getValueAt(fila, 9).toString()));
        dcdat_dalje.setDate(Date.valueOf(listtabele.getValueAt(fila, 10).toString()));
        txtkostoja_e_strehimit.setText(listtabele.getValueAt(fila, 11).toString());
        cbodhoma_e_zene.setSelectedItem(listtabele.getValueAt(fila, 12).toString());
    }//GEN-LAST:event_listtabeleMouseClicked

    private void btnkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoActionPerformed
        // TODO add your handling code here:
        moster(txtkerko.getText());
    }//GEN-LAST:event_btnkerkoActionPerformed

    private void btneliminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminoActionPerformed
        // TODO add your handling code here:
        if (!txtidrezervimi.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "je i sigurt se do ta fshish kete rezervim?","konfirmo",2);

            if (confirmacion==0) {
                frezervimi func = new frezervimi ();
                vrezervimi dts= new vrezervimi();

                dts.setIdrezervimi(Integer.parseInt(txtidrezervimi.getText()));
                func.elimino(dts);
                moster("");
                inavantazh();

            }

        }
    }//GEN-LAST:event_btneliminoActionPerformed

    private void btnshtepiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshtepiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnshtepiActionPerformed

    private void btnverkonsumatoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverkonsumatoriActionPerformed
        // TODO add your handling code here:
        int fila = listtabele.getSelectedRow();
        frmkonsumatori.idrezervimi= listtabele.getValueAt(fila, 0).toString();
        frmkonsumatori.klienti=listtabele.getValueAt(fila, 1).toString();
 
        frmkonsumatori form = new frmkonsumatori();
        frmpamja.pamjet.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnverkonsumatoriActionPerformed

    private void btnrealizimipagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrealizimipagesActionPerformed
        // TODO add your handling code here:
        int fila = listtabele.getSelectedRow();

        frmpaga.idrezervimi = listtabele.getValueAt(fila, 0).toString();
        frmpaga.klienti = listtabele.getValueAt(fila, 1).toString();
        frmpaga.totalrezervimi =Double.parseDouble( listtabele.getValueAt(fila, 2).toString());

        frmpaga.iddhoma = listtabele.getValueAt(fila, 3).toString();
        frmpaga.dhoma = listtabele.getValueAt(fila, 4).toString();

        frmpaga form = new frmpaga();
        frmpamja.pamjet.add(form);
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_btnrealizimipagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmrezervimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmrezervimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmrezervimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmrezervimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmrezervimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.action.ActionContainerFactory actionContainerFactory1;
    private javax.swing.JButton btne_re;
    private javax.swing.JButton btnelimino;
    private javax.swing.JButton btnkancelo;
    private javax.swing.JButton btnkerko;
    private javax.swing.JButton btnkerkodhoma;
    private javax.swing.JButton btnkerkoklienti;
    private javax.swing.JButton btnrealizimipages;
    private javax.swing.JButton btnruaj;
    private javax.swing.JButton btnshtepi;
    private javax.swing.JButton btnverkonsumatori;
    private javax.swing.JComboBox cbodhoma_e_zene;
    private javax.swing.JComboBox cbotipi_rezervimit;
    private com.toedter.calendar.JDateChooser dcdat_dalje;
    private com.toedter.calendar.JDateChooser dcdat_hyrje;
    private com.toedter.calendar.JDateChooser dcdata_rezervimit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbltotalregjister;
    private javax.swing.JTable listtabele;
    public static javax.swing.JTextField txtiddhoma;
    public static javax.swing.JTextField txtidklienti;
    public static javax.swing.JTextField txtidpunonjes;
    private javax.swing.JTextField txtidrezervimi;
    private javax.swing.JTextField txtkerko;
    public static javax.swing.JTextField txtklienti;
    private javax.swing.JTextField txtkostoja_e_strehimit;
    public static javax.swing.JTextField txtnumri;
    public static javax.swing.JTextField txtpunonjes;
    // End of variables declaration//GEN-END:variables
}
