/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prezantimi;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.fdhoma;

/**
 *
 * @author geraldo
 */
public class frmvizitdhoma extends javax.swing.JFrame {

    /**
     * Creates new form frmvizitdhoma
     */
    public frmvizitdhoma() {
        initComponents();
          moster("");
        this.setLocationRelativeTo(null);
        }
    
     void fshehje_kolone() {
        listtabele.getColumnModel().getColumn(0).setMaxWidth(0);
        listtabele.getColumnModel().getColumn(0).setMinWidth(0);
        listtabele.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
     
     void moster(String kerko) {
        try {
            DefaultTableModel model;
            fdhoma func = new fdhoma();
            model = func.mostervizit(kerko);

            listtabele.setModel(model);
            fshehje_kolone();
            lbltotalregjister.setText("Total Regjister " + Integer.toString(func.totalregjister));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtkerko = new javax.swing.JTextField();
        btnkerko = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listtabele = new javax.swing.JTable();
        lbltotalregjister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista e Dhomave"));

        jLabel9.setText("Kerko");

        txtkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkerkoActionPerformed(evt);
            }
        });

        btnkerko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file/kerko.png"))); // NOI18N
        btnkerko.setText("kerko");
        btnkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoActionPerformed(evt);
            }
        });

        listtabele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listtabele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listtabeleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listtabeleMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(listtabele);

        lbltotalregjister.setText("Regjister");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(61, 61, 61)
                        .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnkerko)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltotalregjister)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtkerko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkerko))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltotalregjister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkerkoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkerkoActionPerformed

    private void btnkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoActionPerformed
        // TODO add your handling code here:
        moster(txtkerko.getText());
    }//GEN-LAST:event_btnkerkoActionPerformed

    private void listtabeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listtabeleMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_listtabeleMouseClicked

    private void listtabeleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listtabeleMousePressed
        // TODO add your handling code here:
           if (evt.getClickCount() == 2) {
            int fila= listtabele.getSelectedRow();
            String cod;
            String valor;
            
            cod=listtabele.getValueAt(fila, 0).toString();
            valor=listtabele.getValueAt(fila, 1).toString();
            
            frmrezervimi.txtiddhoma.setText(cod);
            frmrezervimi.txtnumri.setText(valor);
            this.dispose();
            
        }
    }//GEN-LAST:event_listtabeleMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmvizitdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmvizitdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmvizitdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmvizitdhoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmvizitdhoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkerko;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbltotalregjister;
    private javax.swing.JTable listtabele;
    private javax.swing.JTextField txtkerko;
    // End of variables declaration//GEN-END:variables
}
